name: digital_addressing_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6 # Use the latest version

  # For the draggable bottom sheet
  sliding_up_panel: ^2.0.0+1


  provider: ^6.1.1

  # For easy access to a clean, system-like font
  google_fonts: ^6.1.0

  # For the frosted glass effect
  blurrycontainer: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/